services:
  postgres:
    container_name: postgres
    image: postgres:16-alpine
    restart: always
    environment:
      POSTGRES_PASSWORD: ${PGPASSWORD}
      POSTGRES_USER: ${PGUSER}
      POSTGRES_DB: ${PGDATABASE}
      PGPORT: ${PGPORT}
      LANG: ru_RU.utf8
      PGDATA: "/var/lib/postgresql/data/pgdata"
    volumes:
      - pgdata:/var/lib/postgresql/data/pgdata
      - ${PWD}/scripts/docker-entrypoint-initdb:/docker-entrypoint-initdb.d
    ports:
      - ${PGPORT}:${PGPORT}
    command: >
      postgres
      -c shared_buffers=${shared_buffers:-128MB}
      -c effective_cache_size=${effective_cache_size:-512MB}
      -c work_mem=${work_mem:-10MB}
      -c maintenance_work_mem=${maintenance_work_mem:-64MB}
      -c random_page_cost=1.1
      -c effective_io_concurrency=200
      -c max_parallel_workers=2

  sales_control_application:
    container_name: sales_control_application
    image: sales_control_application:latest
    restart: always
    build:
      context: .
      dockerfile: ${PWD}/Dockerfile
    environment:
      PGUSER: ${PGUSER}
      PGPASSWORD: ${PGPASSWORD}
      PGHOST: postgres
      PGPORT: ${PGPORT}
      STATIC_DIR: "/www/data/static"
    ports:
      - 8080:8080
    depends_on:
      - postgres

volumes:
  pgdata:
